---
- name: stop oooq vms
  shell: >
    virsh destroy {{ item }}
  with_items: "{{ vms }}"

- name: remove tripleo vms working dir
  file:
    path: "{{ oooq_vms_path }}"
    state: absent
  become: true

- name: make tripleo vms working dir
  file:
    path: "{{ oooq_vms_path }}"
    state: directory
    group: "{{ oooq_user }}"
    owner: "{{ oooq_user }}"
  become: true

- name: copy undercloud private key
  copy:
    src: "{{ local_working_dir }}/{{ item.file }}"
    dest: "{{ oooq_vms_path }}/{{ item.file }}"
    mode: "{{ item.mode }}"
    group: "{{ oooq_user }}"
    owner: "{{ oooq_user }}"
  with_items: "{{ oooq_files }}"

- name: copy oooq pool
  shell: >
    cp -R {{ pool_path }} {{ oooq_vms_path }}/pool

- name: copy vms xml desc
  shell: >
    cp /home/stack/.config/libvirt/qemu/{{ item }}.xml {{ oooq_vms_path }}
  with_items: "{{ vms }}"

- name: copy oooq pool xml desc
  template:
    src: "{{ item }}"
    dest: "{{ oooq_vms_path }}/{{ item }}"
  with_items:
    - oooq_pool.xml
    - external.xml
    - overcloud.xml

- name: tar oooq_vms
  shell: >
    tar -cvzf {{ oooq_tar_name }} {{ oooq_vms_path }}
