---
- include: backup.yml
  when: backup
  tags:
    - tripleo-backup

- include: restore.yml
  when: restore
  tags:
    - tripleo-restore

- include: sanity.yml
  when: restore
  tags:
    - tripleo-restore-sanity
